default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "academik") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

development:
  <<: *default
  database: academik_development

test:
  <<: *default
  database: academik_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "academik_production") %>
  queue:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "academik_production") %>
    migrations_paths: db/queue_migrate
